### ISSUE TITLE
Getting OpenAir values from broker

### ISSUE THREAD

**Issue by marcel12bell** [OpenAirCgn/openair-firmware-mg#3]
To publish the Data a funktion like  oa_broker_values() would be helpfull to get all values...

mgos_mqtt_pub("my/topic", oa_broker_values);   /* Publish */

**Comment by a2800276** [comment]
I'm not sure what you mean ... `oa_broker_values` already has all the values.  It's an array which contains the last value sensed for each type.

The idea of the broker is that we don't need to buffer the generated values. The broker is basically an internal publish/subscribe mechanism. Consider the [oa_broker_push](https://github.com/OpenAirCgn/openair-firmware-mg/blob/a3e83988cc1e8eb7bc9e1c993777e22173161665/src/broker.c#L114) function (which arguably should be renamed to oa_broker_publish). 

This is where all the sensors end up publishing their sensed values. Currently this function does two things: it stores the value in `oa_broker_values` and, if it's configured to, will send the value via raw tcp to a [server](https://github.com/OpenAirCgn/firehose-server).

This would be a good place to hook up a mqtt backend. Either publish directly from there, or ideally, create a number of configurable data backend that can be used.

Also consider that we don't necessarily want to send _all_ sensed data to the backend, so we may need to accumulate and average, or filter and drop values.

Where would I find information about the current mqtt server (i.e. access data AND which topics it supports & which data types are supported). Maybe I can throw something together next week.

**Comment by marcel12bell** [comment]
For now we have the babeauf.nt.fh-koeln.de with topic mw/openair/ and Message in json lines... (See https://github.com/OpenAirCgn/firmware/blob/master/ESP32_board/ESP32_MQTT_SEND/ESP32_MQTT_SEND.ino)

It would be nice to setup our own openair MQTT server... I could do this. Then we are free on doing what we want...

**Comment by a2800276** [comment]
Ok, is any documentation available concerning the format of the json to send (apart from reading the Arduino source :) ?

How do I get credentials to connect to the server? (Both as a data publisher and as a consumer?)

**Comment by marcel12bell** [comment]
Code ist the documentation ;-)
Line 452 and 465 (https://github.com/OpenAirCgn/firmware/blob/a46a8d9a2051d780d8ce1379f0b7922e9d9e0b30/ESP32_board/ESP32_MQTT_SEND/ESP32_MQTT_SEND.ino#L452)

You find credentials on https://openair.cologne/sensors ... each sensor has his own PW, Topic,... 

We need datapoints every minute, not more...

**Comment by marcel12bell** [comment]
To listen use mw/openair/# and QoS 2 with your credentials

**Comment by a2800276** [comment]
I'm no longer sure what this issue is about, can we close it?

**Comment by a2800276** [comment]
maybe we should open a new one to discuss mqtt

**Comment by marcel12bell** [comment]
Yes, you can close it.
